# Generated by Django 4.1.6 on 2023-02-19 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text="farmer's first name", max_length=20, verbose_name='first name')),
                ('lname', models.CharField(help_text="farmer's last name", max_length=20, verbose_name='last name')),
                ('username', models.CharField(blank=True, help_text="farmer's user name", max_length=50, verbose_name='username')),
                ('phone_number', models.CharField(help_text="farmer's phone number", max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('email', models.EmailField(blank=True, help_text="farmer's email", max_length=254, unique=True, verbose_name='email')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('password', models.CharField(max_length=100, null='false', verbose_name='password')),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(help_text="farmer's country", max_length=25, verbose_name='location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
